const employees = [
    {
      id: 1001,
      name: 'John Doe',
      department: 'Sales',
      jobTitle: 'Sales Manager',
      salary: 80000,
      hireDate: '2020-01-01',
      email: 'john.doe@example.com',
      phoneNumber: '123-456-7890',
      address: '123 Main St, Anytown, USA',
      managerId: null,
      performanceRating: 'Exceeds Expectations',
      reviewDate: '2023-12-31',
    },
    {
      id: 1002,
      name: 'Jane Smith',
      department: 'Marketing',
      jobTitle: 'Marketing Specialist',
      salary: 65000,
      hireDate: '2021-03-15',
      email: 'jane.smith@example.com',
      phoneNumber: '987-654-3210',
      address: '456 Elm St, Anytown, USA',
      managerId: 1001,
      performanceRating: 'Meets Expectations',
      reviewDate: '2023-12-31',
    },
    {
      id: 1003,
      name: 'Michael Johnson',
      department: 'HR',
      jobTitle: 'HR Manager',
      salary: 75000,
      hireDate: '2019-08-20',
      email: 'michael.johnson@example.com',
      phoneNumber: '555-123-4567',
      address: '789 Oak St, Anytown, USA',
      managerId: null,
      performanceRating: 'Needs Improvement',
      reviewDate: '2023-12-31',
    },
    {
      id: 1004,
      name: 'Emily Davis',
      department: 'IT',
      jobTitle: 'Software Engineer',
      salary: 90000,
      hireDate: '2022-05-10',
      email: 'emily.davis@example.com',
      phoneNumber: '444-555-6666',
      address: '1011 Pine St, Anytown, USA',
      managerId: 1003,
      performanceRating: 'Exceeds Expectations',
      reviewDate: '2023-12-31',
    },
    {
      id: 1005,
      name: 'David Lee',
      department: 'Finance',
      jobTitle: 'Accountant',
      salary: 70000,
      hireDate: '2023-02-25',
      email: 'david.lee@example.com',
      phoneNumber: '333-444-5555',
      address: '1212 Maple St, Anytown, USA',
      managerId: null,
      performanceRating: 'Meets Expectations',
      reviewDate: '2023-12-31',
    },
    {
      id: 1006,
      name: 'Sarah Kim',
      department: 'Sales',
      jobTitle: 'Sales Representative',
      salary: 55000,
      hireDate: '2022-10-01',
      email: 'sarah.kim@example.com',
      phoneNumber: '222-333-4444',
      address: '1313 Birch St, Anytown, USA',
      managerId: 1001,
      performanceRating: 'Needs Improvement',
      reviewDate: '2023-12-31',
    },
    {
      id: 1007,
      name: 'Thomas Brown',
      department: 'Marketing',
      jobTitle: 'Marketing Manager',
      salary: 85000,
      hireDate: '2020-07-15',
      email: 'thomas.brown@example.com',
      phoneNumber: '111-222-3333',
      address: '1414 Walnut St, Anytown, USA',
      managerId: null,
      performanceRating: 'Exceeds Expectations',
      reviewDate: '2023-12-31',
    },
    {
      id: 1008,
      name: 'Olivia Taylor',
      department: 'HR',
      jobTitle: 'HR Specialist',
      salary: 60000,
      hireDate: '2021-11-30',
      email: 'olivia.taylor@example.com',
      phoneNumber: '666-777-8888',
      address: '1515 Chestnut St, Anytown, USA',
      managerId: 1003,
      performanceRating: 'Meets Expectations',
      reviewDate: '2023-12-31',
    },
    {
      id: 1009,
      name: 'Ethan Green',
      department: 'IT',
      jobTitle: 'Systems Analyst',
      salary: 80000,
      hireDate: '2023-04-15',
      email: 'ethan.green@example.com',
      phoneNumber: '555-123-4567',
      address: '1616 Cedar St, Anytown, USA',
      managerId: 1004,
      performanceRating: 'Exceeds Expectations',
      reviewDate: '2023-12-31',
    },
    {
      id: 1010,
      name: 'Ava Lee',
      department: 'Finance',
      jobTitle: 'Financial Analyst',
      salary: 75000,
      hireDate: '2022-08-01',
      email: 'ava.lee@example.com',
      phoneNumber: '444-555-6666',
      address: '1717 Willow St, Anytown, USA',
      managerId: null,
      performanceRating: 'Needs Improvement',
      reviewDate: '2023-12-31',
    },
  ];

export default employees;